project_id = "gvylyghwfysvydygqdtf"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.elevenlabs-call-webhook]
    verify_jwt = false
  [functions.greenapi-webhook]
    verify_jwt = false
  [functions.greenapi-webhook-sync]
    verify_jwt = false
  [functions.homely-webhook]
    verify_jwt = false
  [functions.meta-comments-webhook]
    verify_jwt = false
  [functions.meta-dm-webhook]
    verify_jwt = false
  [functions.meta-wa-webhook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.resend-inbound-webhook]
    verify_jwt = false
  [functions.telegram-webhook]
    verify_jwt = false
  [functions.test-webhook]
    verify_jwt = false
  [functions.trial-inbound-webhook]
    verify_jwt = false
  [functions.vapi-tool-handler]
    verify_jwt = false
  [functions.wa-kb-webhook]
    verify_jwt = false
  [functions.whatsapp-webhook]
    verify_jwt = false
