import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.4";
import {
  adminClient,
  loadKbSnippets,
  loadKbInstructions,
  loadKbPostTemplates,
  loadCrmSnapshot,
  renderKbBlock,
  renderKbInstructionsBlock,
  renderKbTemplatesBlock,
  renderCrmBlock,
  ANTI_SPAM_RULES,
  CTA_RULE,
} from "../_shared/grounding.ts";


const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const { topic, platform, customInstructions, selectedListingId, listingFocusOnly } = await req.json();
    if (!topic || !platform) {
      return new Response(JSON.stringify({ error: "topic and platform are required" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) throw new Error("LOVABLE_API_KEY is not configured");

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseAnonKey = Deno.env.get("SUPABASE_ANON_KEY")!;
    const authHeader = req.headers.get("Authorization") ?? "";
    const supabase = createClient(supabaseUrl, supabaseAnonKey, {
      global: { headers: { Authorization: authHeader } },
    });
    const { data: userData } = await supabase.auth.getUser();
    const userId = userData?.user?.id ?? null;

    // Mandatory grounding: workspace KB + live CRM/listings snapshot.
    const admin = adminClient();
    const [kb, kbInstructions, kbTemplates, snap] = await Promise.all([
      loadKbSnippets(admin, userId),
      loadKbInstructions(admin, userId),
      loadKbPostTemplates(admin, userId),
      loadCrmSnapshot(admin, userId),
    ]);
    const kbInstructionsBlock = renderKbInstructionsBlock(kbInstructions);
    const kbTemplatesBlock = renderKbTemplatesBlock(kbTemplates);
    const hasKbTemplate = kbTemplates.length > 0;


    const featureLabels = (features: unknown) => Array.isArray(features)
      ? features
          .map((feature) => typeof feature === "string"
            ? feature
            : feature && typeof feature === "object" && "label" in feature
              ? String((feature as Record<string, unknown>).label ?? "")
              : "")
          .filter(Boolean)
      : [];
    const listingTypeFromFeatures = (features: unknown) => Array.isArray(features)
      ? ((features.find((feature) => feature && typeof feature === "object" && "listing_type" in feature) as Record<string, unknown> | undefined)?.listing_type)
      : null;

    // Fetch a specific promoted listing when supplied by the UI.
    let promotedListing: any = null;
    if (selectedListingId && userId) {
      try {
        const { data: row } = await admin
          .from("listings")
          .select("*")
          .eq("id", selectedListingId)
          .maybeSingle();
        if (row) promotedListing = row;
      } catch { /* non-fatal */ }
    }

    const platformRules: Record<string, string> = {
      instagram: "3-4 משפטים חדים. פתח בהוק קונקרטי על נכס/אזור מתוך ההקשר. 0-1 האשטגים רלוונטיים בלבד.",
      facebook: "3-5 משפטים. פתיחה ספציפית מתוך הנתונים החיים. שפה מקצועית-נגישה.",
      twitter: "מקסימום 280 תווים. ישיר, ממוקד, בלי הקדמות.",
      x: "מקסימום 280 תווים. ישיר, ממוקד, בלי הקדמות.",
      whatsapp: "קצר, ישיר, סגנון מתווך-ללקוח שנשלח מהטלפון.",
      linkedin: "5-7 משפטים בטון יועץ בכיר. תובנה אחת + CTA אחד.",
    };
    const rule = platformRules[String(platform).toLowerCase()] || "קצר, חד, מקצועי.";

    const entropySeed = `${crypto.randomUUID()}-${Date.now()}`;

    const BROKER_PERSONA = `PERSONA (LOCKED — NEVER BREAK CHARACTER):
You are Udi Witman — an elite, top-tier Israeli real-estate broker writing personally from your own phone.
You are a high-achiever shaped by elite sports discipline and complex project management across Israel and the US.
You sell and rent your clients' properties faster and at higher values than anyone else in the market, using deep local intelligence and direct relationships.
You write as a senior advisor closing deals, never as a software, assistant, bot, platform, or tool.`;

    const FORBIDDEN_WORDS = `ABSOLUTE FORBIDDEN VOCABULARY (zero tolerance — if any of these appear, the output is rejected):
- "Realtyz", "ריאלטיז", "Realtyz AI"
- "AI", "בינה מלאכותית", "בוט", "צ'אטבוט", "אלגוריתם", "Algorithm"
- "Platform", "פלטפורמה", "מערכת", "כלי תוכנה", "תוכנה", "אפליקציה", "אוטומציה"
- "as an AI", "I am an AI", "automated message", "generated by"
Never reference any software, vendor, brand, or tool. You are the broker, period. Promote ONLY Udi's brokerage services, achievements, and the real properties from the database/KB.`;

    const customBlock = customInstructions && String(customInstructions).trim()
      ? `[BROKER'S CUSTOM INSTRUCTIONS FOR THIS POST] (highest priority — obey verbatim):\n"""${String(customInstructions).trim().slice(0, 1500)}"""`
      : "";

    const promotedFeatures = promotedListing ? featureLabels(promotedListing.features) : [];
    const promotedListingType = promotedListing ? listingTypeFromFeatures(promotedListing.features) : null;

    const promotedBlock = promotedListing
      ? [
          "[PROMOTED LISTING — THIS POST MUST PROMOTE THIS EXACT PROPERTY] (use ONLY these real fields — never alter prices, address, rooms, or features):",
          promotedListing.property_title ? `כותרת: ${promotedListing.property_title}` : null,
          promotedListingType ? `סוג עסקה: ${promotedListingType === "rent" ? "השכרה" : "מכירה"}` : null,
          promotedListing.address ? `כתובת: ${promotedListing.address}` : null,
          promotedListing.neighborhood ? `שכונה: ${promotedListing.neighborhood}` : null,
          promotedListing.city ? `עיר: ${promotedListing.city}` : null,
          promotedListing.rooms ? `חדרים: ${promotedListing.rooms}` : null,
          promotedListing.sqm ? `שטח: ${promotedListing.sqm} מ"ר` : null,
          promotedListing.floor ? `קומה: ${promotedListing.floor}` : null,
          promotedListing.asking_price ? `מחיר מבוקש: ${Number(promotedListing.asking_price).toLocaleString("he-IL")} ש"ח` : null,
          promotedListing.parking ? `חניה: כן` : null,
          promotedListing.elevator ? `מעלית: כן` : null,
          promotedFeatures.length
            ? `מאפיינים בולטים: ${promotedFeatures.slice(0, 8).join(", ")}`
            : null,
          promotedListing.description ? `תיאור מקצועי קצר: ${String(promotedListing.description).slice(0, 600)}` : null,
        ].filter(Boolean).join("\n")
      : "";

    const focusOnly = !!listingFocusOnly && !!promotedListing;

    const FOCUS_ONLY_RULE = focusOnly ? (hasKbTemplate ? `
LISTING-FOCUS MODE (HARD OVERRIDE — highest priority):
- This post is a direct sales/rental ad for the [PROMOTED LISTING] above and NOTHING else.
- No personal owner story, no broker biography, no market analysis, no neighborhood essay, no testimonials, no philosophy.
- Follow the structure, rhythm, line breaks, sectioning, emoji usage and tone of the [OWNER-AUTHORED POST TEMPLATES FROM KNOWLEDGE BASE] block exactly. Those templates OVERRIDE any built-in default.
- Replace any slot/placeholder with the real listing fields. Skip any line whose data is missing — never invent.
- End with Udi's signature line and 2-3 relevant hashtags only if the KB template uses them.
` : `
LISTING-FOCUS MODE (HARD OVERRIDE — highest priority):
- This post is a direct sales/rental ad for the [PROMOTED LISTING] above and NOTHING else.
- No personal owner story, no broker biography, no market analysis, no neighborhood essay, no testimonials, no philosophy.
- Use the EXACT template structure below (Hebrew, RTL, short lines, blank line between blocks). Each feature line MUST start with a green checkmark emoji "✅ " followed by the text. Replace bracketed slots with the real listing fields. Skip any line whose data is missing — never invent.
- Emojis are allowed ONLY where the template shows them: ✅ for each feature bullet, 📍 once before the address line, 💰 once before the price line, 📞 once before the CTA. Do NOT add other emojis (no 🏠, 🔑, 🌟, ✨, fire, hearts) and never stack multiples.
- End with a CTA inviting WhatsApp/phone, followed by Udi's signature line and 2-3 relevant hashtags.

REFERENCE TEMPLATE (match this rhythm and tone exactly — adapt wording per listing, never copy verbatim):
"""
[חדרים] חדרים ב[עיר] במחיר שכבר קשה למצוא!

📍 [רחוב ומספר] | שכונת [שכונה] | [עיר]

מחפשים [חדרים] חדרים?

[משפט פתיחה אחד קצר על הערך/ההזדמנות של הנכס הספציפי הזה.]

מה תמצאו בדירה?

✅ כ-[שטח] מ"ר
✅ [פיצ'ר 1]
✅ [פיצ'ר 2]
✅ [פיצ'ר 3]
✅ קומה [קומה]
✅ [חניה / מעלית / מיזוג — רק אם קיים]
✅ כניסה [מיידית/בתאריך אם ידוע]

💰 [שכר דירה/מחיר מבוקש]: [מחיר מעוצב] ₪

[משפט סגירה קצר אחד שמדגיש את ההזדמנות.]

📞 אם זה נשמע מעניין, שלחו הודעה או התקשרו

אודי ויטמן | אנגלו סכסון הרצליה/רמ"ש
052-2973500
רישיון תיווך 3251767

#[האשטג1] #[האשטג2] #[האשטג3]
"""`) : "";


    const systemPrompt = `${BROKER_PERSONA}

פלטפורמה: ${platform}
כללי פלטפורמה: ${rule}

${FORBIDDEN_WORDS}
${FOCUS_ONLY_RULE}

GROUNDING POLICY (אפס סובלנות לפיברוק):
- אסור להמציא נכסים, ערים, מחירים, פיצ'רים או נתונים שלא מופיעים במפורש ב-[PROMOTED LISTING] / [LIVE PROPERTIES & CRM CONTEXT] / [WORKSPACE KNOWLEDGE BASE].
- אם יש [PROMOTED LISTING] — הפוסט חייב למקד אותו בלבד עם הפרטים המדויקים מהשורה.
- אם אין נכס ספציפי, דבר מעמדה של מומחיות אישית של אודי (תובנת שוק, ניסיון מהשטח) — בלי להמציא נכס פיקטיבי.
- כל ציטוט של רחוב / עיר / מחיר חייב להופיע מילולית במאגר שלמעלה.

NEIGHBORHOOD-NAMING RULE (HARD):
- לעולם אל תזהה שכונה במספר או בספרות (אסור "שכונה 10", "שכונה ג'", "אזור 7").
- אם יש שם שכונה בעברית בנתונים — השתמש בו בלבד (לדוגמה: "הרצליה הירוקה", "נווה עמל").
- אם אין שם שכונה אמיתי — דלג לחלוטין על שורת השכונה. אל תכתוב "שכונת [שכונה]" ואל תמציא שם.


${ANTI_SPAM_RULES}

${CTA_RULE}
- ה-CTA תמיד מזמין פנייה ישירה לאודי ב-WhatsApp או Messenger (או טלפון למשרד) — מנוסח אחרת בכל פוסט, בלי לציין שום כלי תוכנה.

איסור מוחלט: פוליטיקה, מפלגות, בחירות, וכל הקשר לא-נדל"ני.

כתוב בעברית בלבד, ישראלית טבעית, בגוף ראשון של אודי. החזר את הפוסט בלבד, בלי הסברים נלווים.`;

    const userPrompt = [
      kbTemplatesBlock || null,
      promotedBlock,
      focusOnly ? null : renderCrmBlock(snap),
      focusOnly ? null : renderKbBlock(kb),
      kbInstructionsBlock || null,
      customBlock,
      focusOnly
        ? `מטרת הפוסט: פוסט מכירה/השכרה קצר וישיר לנכס שלמעלה בלבד — בלי שום הקשר אישי, ביוגרפיה או נושאים לא קשורים.`
        : `נושא הפוסט (כיוון כללי מהמשתמש): ${topic}`,
      `Anti-spam entropy seed (vary opener / structure / CTA vs any prior post): ${entropySeed}`,
      focusOnly
        ? `Write a clean, short, scroll-stopping sales post for the ONE listing above. No personal history. No filler.`
        : `Write Udi's post now — grounded strictly in the blocks above. Never mention software/AI/platform/Realtyz.`,
    ].filter(Boolean).join("\n\n");


    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash",
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userPrompt },
        ],
        temperature: 1.0,
        top_p: 0.95,
        presence_penalty: 0.7,
        frequency_penalty: 0.85,
        max_tokens: focusOnly ? 700 : 800,
      }),
    });

    if (!response.ok) {
      if (response.status === 429) {
        return new Response(JSON.stringify({ error: "Rate limit exceeded, please try again later." }), {
          status: 429,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      if (response.status === 402) {
        return new Response(JSON.stringify({ error: "Credits exhausted, please add funds." }), {
          status: 402,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      const t = await response.text();
      console.error("AI gateway error:", response.status, t);
      return new Response(JSON.stringify({ error: "AI generation failed" }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const data = await response.json();
    let content: string = data.choices?.[0]?.message?.content || "";

    // Persona post-processing: strip bullets/markdown/dashes, collapse blank lines.
    content = content
      .replace(/^\s*[-*•]\s+/gm, "")
      .replace(/^\s*\d+[\.)]\s+/gm, "")
      .replace(/[#*_`]+/g, "")
      .replace(/[—–]/g, ",")
      .replace(/--+/g, ",")
      .replace(/\n{3,}/g, "\n\n")
      .trim();

    // HARD SCRUB: forbidden vendor/tech vocabulary must never reach the public.
    const FORBIDDEN_PATTERNS: { re: RegExp; replacement: string }[] = [
      { re: /\brealtyz(?:\s*ai)?\b/gi, replacement: "" },
      { re: /ריאלטיז(?:\s*AI)?/gi, replacement: "" },
      { re: /\bA\.?I\.?\b/g, replacement: "" },
      { re: /בינה\s+מלאכותית/gi, replacement: "מומחיות" },
      { re: /אלגוריתם[ים]*/gi, replacement: "ניסיון" },
      { re: /\b(platform|algorithm)\b/gi, replacement: "" },
      { re: /פלטפורמ[הת]/gi, replacement: "משרד" },
      { re: /\bבוט\b/gi, replacement: "" },
      { re: /צ['׳]?אטבוט/gi, replacement: "" },
      { re: /אוטומצי[הת]/gi, replacement: "" },
    ];
    for (const { re, replacement } of FORBIDDEN_PATTERNS) {
      content = content.replace(re, replacement);
    }
    content = content.replace(/[ \t]{2,}/g, " ").replace(/\n{3,}/g, "\n\n").trim();

    // Neighborhood naming hard rule: never expose numeric/coded neighborhoods.
    // Strip "שכונת [שכונה]" placeholder leftovers and "שכונה 10" / "שכונה ג'" patterns.
    const validNeighborhood = String(promotedListing?.neighborhood ?? "").trim();
    const hasHebrewName = /[\u0590-\u05FF]/.test(validNeighborhood) && !/^\s*\d+\s*$/.test(validNeighborhood);
    content = content
      // "שכונה 10" / "שכונת 7" / "אזור 4" / "שכונת ג'"
      .replace(/(?:שכונ[הת]|אזור)\s+(?:\d+|[א-ת]['׳]?)(?=\s|[,.!?]|$)/g, hasHebrewName ? `שכונת ${validNeighborhood}` : "")
      // unfilled template placeholders like "שכונת [שכונה]"
      .replace(/שכונת\s*\[[^\]]*\]/g, hasHebrewName ? `שכונת ${validNeighborhood}` : "")
      // dangling "| שכונת  |" separators left after removal
      .replace(/\|\s*\|/g, "|")
      .replace(/[ \t]{2,}/g, " ")
      .replace(/\n{3,}/g, "\n\n")
      .trim();


    const p = String(platform).toLowerCase();
    if ((p === "twitter" || p === "x") && content.length > 280) {
      content = content.slice(0, 277).trimEnd() + "...";
    }

    let approvalId: string | null = null;
    if (userData.user) {
      const { data: approval } = await supabase
        .from("approval_queue")
        .insert({
          user_id: userData.user.id,
          content_type: "social_post",
          platform,
          title: `פוסט AI ממתין לאישור - ${topic}`,
          proposed_content: content,
          confidence_score: 78,
          requires_human_review: true,
          low_confidence_reason: "תוכן AI דורש אישור אנושי ואימות מול מאגר הידע לפני פרסום.",
          source_citations: [],
          metadata: {
            topic,
            strict_knowledge: true,
            grounded_listings: snap?.total_listings ?? 0,
            grounded_kb_chars: kb.length,
          },
          created_by_ai: true,
        })
        .select("id")
        .single();
      approvalId = approval?.id ?? null;
    }

    return new Response(
      JSON.stringify({ content, approval_id: approvalId, requires_human_review: true }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } },
    );
  } catch (e) {
    console.error("generate-content error:", e);
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
